"use client";
import { useEffect, useRef, useState } from "react";
import { Video, VideoOff, Mic, MicOff, Headphones, ArrowUpRight, Users, ShieldCheck, LoaderCircle, MonitorUp, PhoneOff, UserPlus, Volume2, LockKeyhole, Minimize2, SwitchCamera } from "lucide-react";
import { Modal, Avatar, , IconButton } from "@/components/ui";
import { Avatar3D } from "@/components/avatar-3d";
import type { Member, Room } from "@/lib/workspace";
import type { CallController, CallMode, DevicePreferences } from "@/hooks/use-call";

export function PrejoinDialog({ room, me, call, devices, onJoined, onClose }: { room: Room; me: Member; call: CallController; devices: DevicePreferences; onJoined: () => void; onClose: () => void }) {
  const [error, setError] = useState("");
  const join = async (mode: CallMode) => { setError(""); try { await call.join(room.id, mode, devices); onJoined(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível entrar na chamada."); } };
  return <Modal title="Pronto para se conectar?" eyebrow="SUA PRÓXIMA BOA CONVERSA" onClose={onClose}><p className="modal-description">Você vai entrar em <strong>{room.name}</strong>. Escolha como quer participar.</p>{call.roomId && call.roomId !== room.id && <div className="demo-profile-note">Ao entrar, você sairá da sua chamada atual.</div>}<div className="prejoin-preview"><div className="prejoin-grid"/><div className="prejoin-avatar"><Avatar3D member={me} size={112} own/></div><span className="prejoin-name">{me.name}</span><span className="preview-media-badge"><MicOff size={13}/><VideoOff size={14}/>Sua privacidade vem primeiro</span></div><div className="prejoin-meta"><span><Users size={14}/>Até {room.capacity} pessoas</span><span><ShieldCheck size={14}/>Conexão ponto a ponto</span></div>{error && <div className="form-error" role="alert">{error}</div>}<div className="prejoin-actions"><button className="button button-primary" disabled={call.connecting} onClick={() => void join("video")}>{call.connecting ? <LoaderCircle size={17} className="spin"/> : <Video size={17}/>}Entrar com vídeo<ArrowUpRight size={15}/></button><button className="button button-secondary" disabled={call.connecting} onClick={() => void join("audio")}><Headphones size={17}/>Somente áudio</button></div><button className="listen-button" disabled={call.connecting} onClick={() => void join("listen")}>Entrar apenas para ouvir</button><p className="modal-footnote">A câmera e o microfone só serão acessados depois da sua permissão. Somente pessoas cadastradas participam de chamadas.</p></Modal>;
}
function VideoTile({ member, stream, local = false, cameraOn, micOn, sharing = false, volume = 80 }: { member: Member; stream?: MediaStream | null; local?: boolean; cameraOn: boolean; micOn: boolean; sharing?: boolean; volume?: number }) {
  const ref = useRef<HTMLVideoElement>(null); const [blocked, setBlocked] = useState(false);
  useEffect(() => {
    const video = ref.current; if (!video) return;
    video.srcObject = stream || null;
    if (stream) video.play().then(() => setBlocked(false)).catch(() => setBlocked(true));
    return () => { video.srcObject = null; };
  }, [stream]);
  useEffect(() => {
    // Volume não deve reanexar o stream (isso reiniciava vídeo/áudio a cada
    // ajuste do slider) — só ajusta o elemento já conectado.
    const video = ref.current; if (video) video.volume = volume / 100;
  }, [volume]);
  return <div className={`video-tile ${local ? "local-tile" : ""} ${sharing ? "screen-tile" : ""}`}><div className="video-placeholder" style={{ background: `radial-gradient(ellipse at center, ${member.color}20, transparent 75%)` }}><Avatar member={member} size={76}/><span>{!local && !stream ? "Conectando…" : cameraOn ? "Preparando vídeo…" : "Câmera desativada"}</span></div><video ref={ref} autoPlay playsInline muted={local} className={cameraOn || sharing ? "video-visible" : "video-hidden"}/><div className="video-tile-label"><span>{member.name}{local && " (você)"}</span>{sharing ? <span className="sharing-label"><MonitorUp size={13}/>Apresentando</span> : micOn ? <Mic size={14}/> : <MicOff size={14}/>}</div>{blocked && !local && <button className="video-play-button button button-secondary" onClick={() => void ref.current?.play().then(() => setBlocked(false))}><Volume2 size={16}/>Ativar áudio</button>}</div>;
}
export function ActiveCallDialog({ room, me, call, onMinimize, onInvite, volume }: { room: Room; me: Member; call: CallController; onMinimize: () => void; onInvite: () => void; volume: number }) {
  const remote = call.participants.filter(p => p.id !== me.id);
  return <Modal title={room.name} eyebrow="CONECTADOS PARA CONSTRUIR" onClose={onMinimize} wide className="active-call-modal"><div className="call-subheading"><span><span className="small-status-dot available"/>{remote.length + 1} {remote.length ? "pessoas na chamada" : "pessoa na chamada"}</span><button className="text-link" onClick={onMinimize}><Minimize2 size={13}/>Minimizar</button></div><div className={`video-grid ${remote.length > 1 ? "many-videos" : ""}`}><VideoTile member={me} stream={call.screenStream || call.localStream} local cameraOn={call.cameraOn} micOn={call.micOn} sharing={!!call.screenStream}/>{remote.map(member => <VideoTile key={member.id} member={member} stream={call.remoteStreams[member.id]} cameraOn={member.cameraEnabled} micOn={member.micEnabled} volume={volume}/>)}{!remote.length && <div className="call-waiting"><span><Users size={31} strokeWidth={1.4}/></span><h3>Sua próxima conexão<br/>começa aqui.</h3><p>A sala está pronta. Convide sua equipe<br/>e faça a conversa acontecer.</p><button className="button button-secondary" onClick={onInvite}><UserPlus size={15}/>Convidar pessoas</button></div>}</div><div className="call-control-bar"><div className="call-media-controls"><IconButton label={call.micOn ? "Desativar microfone" : "Ativar microfone"} className={call.micOn ? "enabled" : "media-off"} onClick={() => void call.toggleMic()}>{call.micOn ? <Mic size={20}/> : <MicOff size={20}/>}</IconButton><IconButton label={call.cameraOn ? "Desativar câmera" : "Ativar câmera"} className={call.cameraOn ? "enabled" : "media-off"} onClick={() => void call.toggleCamera()}>{call.cameraOn ? <Video size={21}/> : <VideoOff size={21}/>}</IconButton>{call.cameraOn && <IconButton label={call.cameraFacing === "user" ? "Usar câmera traseira" : "Usar câmera frontal"} className="camera-switch-control" onClick={() => void call.switchCamera()}><SwitchCamera size={20}/></IconButton>}<IconButton label={call.screenStream ? "Parar compartilhamento" : "Compartilhar tela"} className={call.screenStream ? "enabled" : ""} onClick={() => void call.shareScreen()}><MonitorUp size={20}/></IconButton><IconButton label="Convidar participantes" onClick={onInvite}><UserPlus size={20}/></IconButton></div><button className="button button-danger" onClick={() => { void call.leave(); onMinimize(); }}><PhoneOff size={17}/>Sair da chamada</button></div><p className="call-security"><LockKeyhole size={12}/>Áudio e vídeo criptografados entre os participantes.</p></Modal>;
}
