"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { UserPlus, Check, Copy, Mail, Link2, LoaderCircle, CalendarDays, Clock3, Users, ArrowUpRight, Search, Monitor, Mic, Video, Volume2, Sparkles, MousePointer2, Headphones, ShieldCheck, ExternalLink, MapPin, Building2, Download, Trash2, ChevronRight, KeyRound, Globe } from "lucide-react";
import { Modal, Avatar, BrandMark, RoomIcon, EmptyState } from "@/components/ui";
import { AvatarStudio } from "@/components/avatar-studio";
import { parseLook, serializeLook, type AvatarLook } from "@/lib/avatar";
import { EcosystemLogo, InstagramGlyph } from "@/components/ecosystem-nav";
import { ecosystemByName } from "@/lib/ecosystem";
import { api, COMPANY_DATA, STATUS_LABELS, timeLabel, dayLabel, type Member, type Workspace, type Meeting, type Room } from "@/lib/workspace";
import type { DevicePreferences } from "@/hooks/use-call";
export type Preferences = DevicePreferences & { volume: number; reduceMotion: boolean; notifications: boolean };
export const DEFAULT_PREFERENCES: Preferences = { volume: 80, reduceMotion: false, notifications: true };

export function ProfileDialog({ me, onSave, onSaveCredentials, onClose }: { me: Member; onSave: (patch: Partial<Member>) => Promise<void>; onSaveCredentials?: (email: string, password: string) => Promise<void>; onClose: () => void }) {
  const [name, setName] = useState(me.name); const [role, setRole] = useState(me.role); const [company, setCompany] = useState(me.company); const [color, setColor] = useState(me.color); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [look, setLook] = useState<AvatarLook>(() => parseLook(me.avatarLook, me.id));
  const [confirmPassword, setConfirmPassword] = useState(""); const [credError, setCredError] = useState(""); const [password, setPassword] = useState(""); const [email, setEmail] = useState(""); const [credBusy, setCredBusy] = useState(false); const [credSaved, setCredSaved] = useState(false);
  useEffect(() => { setEmail(""); }, [me.id]);
  const submitCredentials = async (event: FormEvent) => { event.preventDefault(); setCredBusy(true); setCredError(""); setCredSaved(false); try { if (password.length < 8) throw new Error("A senha deve ter ao menos 8 caracteres."); if (password !== confirmPassword) throw new Error("As senhas não coincidem."); await onSaveCredentials!(email.trim(), password); setCredSaved(true); setPassword(""); setConfirmPassword(""); } catch (err) { setCredError(err instanceof Error ? err.message : "Não foi possível salvar suas credenciais."); } finally { setCredBusy(false); } };
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(""); try { await onSave({ name: name.trim(), role: role.trim(), company, color, avatarLook: serializeLook(look), ...(name !== me.name ? { avatar: "" } : {}) }); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível salvar."); } finally { setBusy(false); } };
  return <Modal title="Estúdio do avatar" eyebrow="DO SEU JEITO" onClose={onClose} wide className="profile-studio-modal"><p className="modal-description">Escolha pele, cabelo, traje e detalhes. Cada conexão começa com você — e agora dá para ver isso no mapa.</p><form onSubmit={submit}><AvatarStudio look={look} color={color} gender={me.gender} onChange={setLook} onColor={setColor} /><label className="form-field"><span>Seu nome</span><input required minLength={2} maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="Como a equipe pode chamar você?" autoComplete="name"/></label><div className="form-row"><label className="form-field"><span>Cargo ou área</span><input required minLength={2} maxLength={80} value={role} onChange={e => setRole(e.target.value)} placeholder="Seu papel na equipe"/></label><label className="form-field"><span>Empresa</span><select value={company} onChange={e => setCompany(e.target.value)}>{COMPANY_DATA.map(c => <option key={c.name}>{c.name}</option>)}<option>GX Hub</option><option>Empresa parceira</option></select></label></div>{error && <div className="form-error" role="alert">{error}</div>}<button type="submit" className="button button-primary full-width" disabled={busy}>{busy ? <LoaderCircle size={17} className="spin"/> : <Check size={17}/>} Salvar meu avatar</button><p className="modal-footnote">Seu perfil acompanha você em todos os ambientes do workspace.</p>{onSaveCredentials && <div className="credentials-section"><h3>Acesso por email e senha</h3><p className="modal-description">Configure o email e a senha usados para entrar como administrador. Guarde com segurança.</p>{credSaved && <div className="credentials-ok"><Check size={15}/>Email e senha atualizados com sucesso.</div>}<form onSubmit={submitCredentials}><label className="form-field"><span>Email</span><input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="seu.email@exemplo.com" autoComplete="email"/></label><div className="form-row"><label className="form-field"><span>Senha</span><input type="password" required minLength={8} value={password} onChange={e => setPassword(e.target.value)} placeholder="Nova senha" autoComplete="new-password"/></label><label className="form-field"><span>Confirmar senha</span><input type="password" required minLength={8} value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} placeholder="Repita a senha" autoComplete="new-password"/></label></div>{credError && <div className="form-error" role="alert">{credError}</div>}<button type="submit" className="button button-secondary full-width" disabled={credBusy}>{credBusy ? <LoaderCircle size={17} className="spin"/> : <KeyRound size={17}/>} Salvar email e senha</button></form></div>}</form></Modal>;
}
export function InviteDialog({ roomId, onClose }: { roomId?: string | null; onClose: () => void }) {
  const [link, setLink] = useState(""); const [error, setError] = useState(""); const [copied, setCopied] = useState(false); const [expires, setExpires] = useState(""); const field = useRef<HTMLInputElement>(null);
  const create = async () => { setError(""); try { const result = await api<{ token: string; expiresAt: string }>("/api/invites", { method: "POST" }); setLink(`${window.location.origin}/?invite=${result.token}${roomId ? `&room=${encodeURIComponent(roomId)}` : ""}`); setExpires(dayLabel(result.expiresAt)); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível criar o convite."); } };
  useEffect(() => {
    let active = true;
    void api<{ token: string; expiresAt: string }>("/api/invites", { method: "POST" })
      .then(result => {
        if (!active) return;
        setLink(`${window.location.origin}/?invite=${result.token}${roomId ? `&room=${encodeURIComponent(roomId)}` : ""}`);
        setExpires(dayLabel(result.expiresAt));
      })
      .catch(err => {
        if (!active) return;
        setError(err instanceof Error ? err.message : "Não foi possível criar o convite.");
      });
    return () => { active = false; };
  }, [roomId]);
  const copy = async () => { try { if (navigator.clipboard) await navigator.clipboard.writeText(link); else { field.current?.select(); if (!document.execCommand("copy")) throw new Error(); } setCopied(true); setTimeout(() => setCopied(false), 2500); } catch { field.current?.select(); setError("Selecione o link e use Ctrl+C ou ⌘C para copiar."); } };
  return <Modal title="Boas conexões merecem companhia." eyebrow="CONVIDE SUA EQUIPE" onClose={onClose}><div className="invite-illustration"><span className="invite-circle invite-circle-one">GX</span><span className="invite-dotted-line"/><span className="invite-main-icon"><UserPlus size={30} strokeWidth={1.4}/></span><span className="invite-dotted-line"/><span className="invite-circle invite-circle-two"><Users size={20}/></span></div><p className="modal-description centered">Compartilhe o cadastro no escritório Grupo X.<br/>A próxima grande ideia pode vir dessa conexão.</p><label className="field-label">Link de convite do workspace</label><div className="invite-link-field"><Link2 size={16}/><input ref={field} readOnly aria-label="Link de convite" value={link} placeholder="Preparando seu convite..." onFocus={e => e.target.select()}/><button onClick={() => void copy()} disabled={!link} aria-label="Copiar link de convite">{copied ? <Check size={17}/> : link ? <Copy size={17}/> : <LoaderCircle size={17} className="spin"/>}</button></div>{error && <div className="form-error" role="alert">{error}{!link && <button className="text-link" onClick={() => void create()}>Tentar novamente</button>}</div>}<button className="button button-primary full-width" disabled={!link} onClick={() => void copy()}>{copied ? <Check size={16}/> : <Copy size={16}/>} {copied ? "Link copiado!" : "Copiar link de convite"}</button><a className={`button button-secondary full-width invite-email ${!link ? "disabled" : ""}`} href={`mailto:?subject=${encodeURIComponent("Seu lugar no escritório Grupo X")}&body=${encodeURIComponent(`Vamos construir juntos? Entre no nosso escritório virtual GX Hub: ${link}`)}`}><Mail size={16}/>Convidar por e-mail<ArrowUpRight size={14}/></a><p className="invite-validity"><ShieldCheck size={13}/>{expires ? `Convite de visitante válido até ${expires}` : "Convite válido por 7 dias"}</p><p className="modal-footnote">Quem abrir este link poderá se cadastrar e entrar no escritório. Compartilhe apenas com sua equipe.</p></Modal>;
}
function localDateTime(date: Date) {
  const adjusted = new Date(date.getTime() - date.getTimezoneOffset() * 60000);
  return adjusted.toISOString().slice(0, 16);
}

export function ScheduleDialog({ rooms, onSaved, onClose }: { rooms: Room[]; onSaved: () => void; onClose: () => void }) {
  const [now] = useState(() => new Date());
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [roomId, setRoomId] = useState("estrategia");
  const [when, setWhen] = useState(() => {
    const nextHour = new Date(now);
    nextHour.setHours(nextHour.getHours() + 1, 0, 0, 0);
    return localDateTime(nextHour);
  });
  const [duration, setDuration] = useState("30");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError("");
    try {
      await api("/api/meetings", {
        method: "POST",
        body: JSON.stringify({
          title,
          description,
          roomId,
          startsAt: new Date(when).toISOString(),
          duration: Number(duration),
        }),
      });
      onSaved();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Não foi possível agendar.");
    } finally {
      setBusy(false);
    }
  };
  return <Modal title="Reserve um tempo para conectar." eyebrow="NOVA REUNIÃO" onClose={onClose}><p className="modal-description">Um propósito em comum, um espaço para conversar.</p><form onSubmit={submit}><label className="form-field"><span>Nome da reunião</span><input required minLength={3} maxLength={100} value={title} onChange={e => setTitle(e.target.value)} placeholder="Ex.: Alinhamento de estratégia"/></label><label className="form-field"><span>Ambiente</span><select value={roomId} onChange={e => setRoomId(e.target.value)}>{rooms.map(room => <option value={room.id} key={room.id}>{room.name} · até {room.capacity} pessoas</option>)}</select></label><div className="form-row date-form-row"><label className="form-field"><span>Data e horário</span><input type="datetime-local" required value={when} onChange={e => setWhen(e.target.value)}/></label><label className="form-field"><span>Duração</span><select value={duration} onChange={e => setDuration(e.target.value)}>{[15, 30, 45, 60, 90, 120].map(value => <option value={value} key={value}>{value} minutos</option>)}</select></label></div><label className="form-field"><span>Sobre a conversa <small>opcional</small></span><textarea rows={3} maxLength={2000} placeholder="O que vamos construir juntos?" value={description} onChange={e => setDescription(e.target.value)}/></label>{error && <div className="form-error" role="alert">{error}</div>}<button type="submit" className="button button-primary full-width" disabled={busy}>{busy ? <LoaderCircle size={17} className="spin"/> : <CalendarDays size={17}/>}Agendar reunião</button><p className="modal-footnote">O encontro ficará visível para toda a equipe na agenda do workspace. Horários no fuso do seu dispositivo.</p></form></Modal>;
}
export function MeetingDialog({ meeting, data, onJoin, onClientInvite, onCancelled, onClose }: { meeting: Meeting; data: Workspace; onJoin: (room: Room) => void; onClientInvite?: () => void; onCancelled: () => void; onClose: () => void }) {
  const room = data.rooms.find(r => r.id === meeting.roomId)!; const organizer = data.team.find(m => m.id === meeting.organizerId) || data.members.find(m => m.id === meeting.organizerId);
  const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const download = () => {
    const format = (d: Date) => d.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
    const escape = (s: string) => s.replace(/\\/g, "\\\\").replace(/\n/g, "\\n").replace(/,/g, "\\,").replace(/;/g, "\\;");
    const content = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//GX Hub//Workspace//PT", "BEGIN:VEVENT", `UID:${meeting.id}@gxhub`, `DTSTAMP:${format(new Date())}`, `DTSTART:${format(new Date(meeting.startsAt))}`, `DTEND:${format(new Date(new Date(meeting.startsAt).getTime() + meeting.duration * 60000))}`, `SUMMARY:${escape(meeting.title)}`, `DESCRIPTION:${escape(meeting.description)}`, `LOCATION:${escape(`GX Hub - ${room.name}`)}`, "END:VEVENT", "END:VCALENDAR"].join("\r\n");
    const url = URL.createObjectURL(new Blob([content], { type: "text/calendar;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "reuniao-gx-hub.ics"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  const cancel = async () => { if (!confirm) { setConfirm(true); return; } setBusy(true); try { await api(`/api/meetings?id=${encodeURIComponent(meeting.id)}`, { method: "DELETE" }); onCancelled(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível cancelar."); } finally { setBusy(false); } };
  return <Modal title={meeting.title} eyebrow="UM ENCONTRO PARA CONSTRUIR" onClose={onClose}><div className="meeting-detail-banner"><span><CalendarDays size={26} strokeWidth={1.5}/></span><div><strong>{new Date(meeting.startsAt).toLocaleDateString("pt-BR", { weekday: "long", day: "numeric", month: "long" })}</strong><p>{timeLabel(meeting.startsAt)} – {timeLabel(new Date(new Date(meeting.startsAt).getTime() + meeting.duration * 60000))}</p></div></div><p className="meeting-description">{meeting.description || "Um espaço para compartilhar ideias e definir os próximos passos juntos."}</p><div className="meeting-detail-rows"><div><MapPin size={17}/><span>Ambiente</span><strong>{room.name}</strong></div><div><Clock3 size={17}/><span>Duração</span><strong>{meeting.duration} minutos</strong></div><div><Users size={17}/><span>Organização</span><strong>{organizer?.name || "Equipe Grupo X"}</strong></div></div>{data.me.isAdmin && onClientInvite && <button className="button button-secondary full-width client-invite-button" onClick={onClientInvite}><UserPlus size={16}/>Criar convite de cliente</button>}<button className="button button-primary full-width" onClick={() => onJoin(room)}><Video size={17}/>Entrar na sala<ArrowUpRight size={16}/></button><button className="button button-secondary full-width calendar-download" onClick={download}><Download size={16}/>Adicionar ao meu calendário</button>{meeting.organizerId === data.me.id && <button className="cancel-meeting" disabled={busy} onClick={() => void cancel()}><Trash2 size={14}/>{busy ? "Cancelando…" : confirm ? "Confirmar cancelamento da reunião" : "Cancelar reunião"}</button>}{error && <div className="form-error" role="alert">{error}</div>}</Modal>;
}
export function MemberDialog({ member, rooms, own, onProfile, onVisit, onJoin, onClose }: { member: Member; rooms: Room[]; own: boolean; onProfile: () => void; onVisit: (id: string) => void; onJoin: (room: Room) => void; onClose: () => void }) {
  const room = rooms.find(r => r.id === member.roomId) || rooms[0];
  return <Modal title="Pessoas que fazem acontecer." eyebrow="CONEXÕES DO ECOSSISTEMA" onClose={onClose}><div className="member-profile-hero"><Avatar member={member} size={78} status/><h3>{member.name}{member.isAdmin && <span className="admin-chip"><ShieldCheck size={11}/>admin</span>}</h3><p>{member.role}</p><span>{member.company}</span></div><div className="member-profile-status"><span className={`small-status-dot ${member.status}`}/>{STATUS_LABELS[member.status]}<span className="profile-status-divider"/><RoomIcon kind={room.kind} size={14}/>{room.name}</div><div className="member-bio"><span className="field-label">NOSSA CULTURA, EM CADA CONEXÃO</span><p>Estratégia que direciona. Parceria que conecta.<br/>Resultados que transformam.</p></div>{own ? <button className="button button-primary full-width" onClick={onProfile}>Personalizar meu perfil<ArrowUpRight size={15}/></button> : <div className="form-row"><button className="button button-secondary" onClick={() => onVisit(room.id)}><MapPin size={15}/>Ver no escritório</button><button className="button button-primary" onClick={() => onJoin(room)}><Headphones size={16}/>Abrir ambiente</button></div>}</Modal>;
}
export function SettingsDialog({ preferences, onSave, onClose }: { preferences: Preferences; onSave: (value: Preferences) => void; onClose: () => void }) {
  const [value, setValue] = useState(preferences); const [devices, setDevices] = useState<MediaDeviceInfo[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const detect = async () => { setBusy(true); setError(""); let stream: MediaStream | undefined; try { if (!navigator.mediaDevices) throw new Error("Use uma conexão HTTPS para acessar os dispositivos."); try { stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: true }); } catch (err) { if (err instanceof DOMException && err.name === "NotFoundError") stream = await navigator.mediaDevices.getUserMedia({ audio: true }); else throw err; } setDevices(await navigator.mediaDevices.enumerateDevices()); } catch (err) { setError(err instanceof Error && err.message.includes("HTTPS") ? err.message : "Permita o acesso à câmera e ao microfone no navegador para listar seus dispositivos."); } finally { stream?.getTracks().forEach(track => track.stop()); setBusy(false); } };
  return <Modal title="Uma conexão do seu jeito." eyebrow="PREFERÊNCIAS DO DISPOSITIVO" onClose={onClose}><p className="modal-description">Ajuste os detalhes para se sentir ainda mais perto.</p><div className="settings-section-label"><Monitor size={16}/><h3>Áudio e vídeo</h3><button className="text-link" disabled={busy} onClick={() => void detect()}>{busy ? <LoaderCircle size={13} className="spin"/> : "Detectar dispositivos"}</button></div><label className="form-field"><span><Mic size={13}/>Microfone</span><select aria-label="Microfone" value={value.audioId || ""} onChange={e => setValue({ ...value, audioId: e.target.value })}><option value="">Padrão do sistema</option>{devices.filter(d => d.kind === "audioinput").map((d, i) => <option key={d.deviceId} value={d.deviceId}>{d.label || `Microfone ${i + 1}`}</option>)}</select></label><label className="form-field"><span><Video size={14}/>Câmera</span><select aria-label="Câmera" value={value.videoId || ""} onChange={e => setValue({ ...value, videoId: e.target.value })}><option value="">Padrão do sistema</option>{devices.filter(d => d.kind === "videoinput").map((d, i) => <option key={d.deviceId} value={d.deviceId}>{d.label || `Câmera ${i + 1}`}</option>)}</select></label><label className="volume-setting"><span><Volume2 size={15}/>Volume das chamadas<strong>{value.volume}%</strong></span><input aria-label="Volume das chamadas" type="range" min="0" max="100" value={value.volume} onChange={e => setValue({ ...value, volume: Number(e.target.value) })}/></label><div className="settings-toggles"><label><span><strong>Sons de novas mensagens</strong><small>Um toque sutil para não perder uma conexão.</small></span><input type="checkbox" checked={value.notifications} onChange={e => setValue({ ...value, notifications: e.target.checked })}/></label><label><span><strong>Reduzir animações</strong><small>Uma experiência visual mais tranquila.</small></span><input type="checkbox" checked={value.reduceMotion} onChange={e => setValue({ ...value, reduceMotion: e.target.checked })}/></label></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="button button-primary full-width" onClick={() => onSave(value)}><Check size={16}/>Salvar preferências</button><p className="modal-footnote">Preferências salvas apenas neste dispositivo. Detectar dispositivos não inicia uma chamada.</p></Modal>;
}
export function HelpDialog({ onClose, onInvite }: { onClose: () => void; onInvite: () => void }) {
  return <Modal title="Sinta-se em casa. Estamos juntos." eyebrow="BEM-VINDO AO GX HUB" onClose={onClose}><p className="modal-description">Seu escritório virtual, com a proximidade de estar lado a lado.</p><div className="help-steps"><article><span><MousePointer2 size={21}/></span><div><h3>Explore, encontre, conecte.</h3><p>Clique no chão para mover seu avatar. Com o mapa em foco, use as setas ou W, A, S, D. Clique em um ambiente para visitá-lo.</p></div></article><article><span><Headphones size={21}/></span><div><h3>Uma conversa está a um clique.</h3><p>Entre em uma sala com áudio, vídeo ou apenas para ouvir. Ative o microfone, compartilhe a tela e faça a conversa acontecer.</p></div></article><article><span><UserPlus size={21}/></span><div><h3>O escritório é melhor com a equipe.</h3><p>O administrador cadastra cada pessoa, que entra escolhendo seu nome na tela de acesso. Pessoas em outros dispositivos aparecem no mapa e podem conversar com você.</p></div></article></div><div className="demo-profile-note"><Sparkles size={17}/><p><strong>Acesso da equipe</strong>Somente pessoas cadastradas entram no escritório. O administrador gerencia cadastros na aba Equipe. Chamadas usam WebRTC ponto a ponto; redes restritas podem exigir um servidor TURN.</p></div><button className="button button-primary full-width" onClick={onInvite}><UserPlus size={16}/>Convidar minha equipe</button><a className="help-contact text-link" href="mailto:contato.gxhub@gmail.com">Precisa de ajuda? Fale com o Grupo X<ArrowUpRight size={13}/></a></Modal>;
}
export function SearchDialog({ data, onMember, onRoom, onMeeting, onClose }: { data: Workspace; onMember: (m: Member) => void; onRoom: (id: string) => void; onMeeting: (m: Meeting) => void; onClose: () => void }) {
  const [query, setQuery] = useState(""); const field = useRef<HTMLInputElement>(null);
  useEffect(() => { const timer = setTimeout(() => field.current?.focus(), 80); return () => clearTimeout(timer); }, []);
  const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const matches = (value: string) => normalize(value).includes(normalize(query));
  const rooms = data.rooms.filter(r => matches(r.name)); const members = data.team.filter(m => matches(`${m.name} ${m.company}`)); const meetings = data.meetings.filter(m => matches(m.title));
  return <Modal title="Encontre sua próxima conexão." eyebrow="BUSCAR NO WORKSPACE" onClose={onClose}><label className="search-field global-search-field"><Search size={18}/><input ref={field} value={query} onChange={e => setQuery(e.target.value)} placeholder="Pessoas, ambientes ou reuniões..." aria-label="Buscar no workspace"/></label><div className="search-results">{!!rooms.length && <section><h3>AMBIENTES</h3>{rooms.map(room => <button key={room.id} onClick={() => onRoom(room.id)}><span className="search-result-icon"><RoomIcon kind={room.kind}/></span><span><strong>{room.name}</strong><small>Até {room.capacity} pessoas</small></span><ArrowUpRight size={15}/></button>)}</section>}{!!members.length && <section><h3>PESSOAS</h3>{members.slice(0, 8).map(member => <button key={member.id} onClick={() => onMember(member)}><Avatar member={member} size={32}/><span><strong>{member.name}</strong><small>{member.company} · {member.role}</small></span><ArrowUpRight size={15}/></button>)}</section>}{!!meetings.length && <section><h3>REUNIÕES</h3>{meetings.slice(0, 5).map(meeting => <button key={meeting.id} onClick={() => onMeeting(meeting)}><span className="search-result-icon"><CalendarDays size={17}/></span><span><strong>{meeting.title}</strong><small>{dayLabel(meeting.startsAt)} · {timeLabel(meeting.startsAt)}</small></span><ArrowUpRight size={15}/></button>)}</section>}{!rooms.length && !members.length && !meetings.length && <EmptyState icon={<Search size={28}/>} title="Ainda não encontramos." description="Tente buscar com outro nome ou palavra-chave."/>}</div></Modal>;
}
export function CompanyDialog({ name, onClose }: { name?: string; onClose: () => void }) {
  const companies = name ? COMPANY_DATA.filter(c => c.name === name) : COMPANY_DATA;
  const selected = name ? ecosystemByName(name) : undefined;
  const primaryHref = selected?.href || "https://grupox.lovable.app/";
  const primaryLabel = selected?.id === "senna-cell-x" ? "Conheça a Senna Cell X" : selected ? `Abrir Instagram do ${selected.name}` : "Conheça o Grupo X";
  return <Modal title={name || "Empresas diferentes. Uma só visão."} eyebrow="ECOSSISTEMA GRUPO X" onClose={onClose}><div className="ecosystem-intro">{selected ? <EcosystemLogo company={selected} size={90} /> : <BrandMark size={63}/>}<p>{selected?.description || "Estratégia, pessoas e execução conectadas para transformar crescimento em um processo sustentável."}</p></div><div className="ecosystem-companies">{companies.map(company => { const eco = ecosystemByName(company.name); return <article key={company.name}>{eco ? <EcosystemLogo company={eco} /> : <span style={{ color: company.color }}><Building2 size={23} strokeWidth={1.5}/></span>}<div><h3>{company.name}</h3><span>{company.category}</span><p>{eco?.description || company.description}</p>{eco && <div className="ecosystem-company-links">{eco.id === "senna-cell-x" ? <a href={eco.href} target="_blank" rel="noopener noreferrer" aria-label={eco.hrefLabel}><Globe size={13}/>Website</a> : null}<a href={eco.instagram || eco.href} target="_blank" rel="noopener noreferrer" aria-label={`Abrir canal oficial de ${eco.name} em nova aba`}><InstagramGlyph size={13}/>{eco.instagram ? "Instagram" : "Canal oficial"}</a></div>}</div></article>; })}</div><a className="button button-primary full-width" href={primaryHref} target="_blank" rel="noopener noreferrer">{primaryLabel}<ExternalLink size={15}/></a><p className="modal-footnote">Mais que gestão. Parceria para a vida.</p></Modal>;
}
