"use client";
import { useState } from "react";
import { ArrowUpRight, ArrowRight, CalendarDays, Clock3, Video, Users, Search, Plus, ChevronLeft, ChevronRight, SlidersHorizontal, UserPlus, Coffee, Check } from "lucide-react";
import { Avatar, RoomIcon, EmptyState } from "@/components/ui";
import { timeLabel, dayLabel, STATUS_LABELS, isOnline, type Workspace, type Meeting, type Room, type Member } from "@/lib/workspace";

export function MeetingsPreview({ data, onAgenda, onMeeting }: { data: Workspace; onAgenda: () => void; onMeeting: (meeting: Meeting) => void }) {
  const [now] = useState(() => Date.now());
  const upcoming = data.meetings.filter(m => new Date(m.startsAt).getTime() + m.duration * 60000 > now).slice(0, 2);
  return <section className="upcoming-section"><div className="section-heading"><h2>Próximas conexões<span>Um tempo para construir juntos.</span></h2><button className="text-link" onClick={onAgenda}>Ver agenda<ArrowUpRight size={14}/></button></div><div className="upcoming-grid">{upcoming.map((meeting, index) => <button className="upcoming-card" key={meeting.id} onClick={() => onMeeting(meeting)}><span className={`meeting-card-icon ${index ? "sage" : ""}`}>{index ? <Users size={20} strokeWidth={1.5}/> : <CalendarDays size={20} strokeWidth={1.5}/>}</span><span className="meeting-card-content"><strong>{meeting.title}</strong><span><Clock3 size={11}/>{timeLabel(meeting.startsAt)}<i/> {data.rooms.find(r => r.id === meeting.roomId)?.name}</span></span><span className="meeting-card-date">{dayLabel(meeting.startsAt)}<ArrowUpRight size={16}/></span></button>)}{!upcoming.length && <button className="upcoming-empty" onClick={onAgenda}><CalendarDays size={20}/><span>Sua próxima grande conversa ainda está por vir.</span><span className="text-gold">Agendar <Plus size={14}/></span></button>}</div></section>;
}
export function RoomsView({ data, onJoin, onVisit, onSchedule }: { data: Workspace; onJoin: (room: Room) => void; onVisit: (id: string) => void; onSchedule: () => void }) {
  const [filter, setFilter] = useState("all");
  const filtered = data.rooms.filter(room => (room.id !== "diretoria" || data.me.isAdmin) && (filter === "all" || (filter === "work" ? ["work", "reception"].includes(room.kind) : filter === "meeting" ? ["meeting", "private"].includes(room.kind) : room.kind === "lounge")));
  return <div className="view-content"><div className="view-filter-bar"><div className="segmented-tabs">{[["all", "Todos os ambientes"], ["work", "Colaboração"], ["meeting", "Reuniões"], ["lounge", "Pausa & conexão"]].map(([id, label]) => <button key={id} className={filter === id ? "active" : ""} onClick={() => setFilter(id)}>{label}</button>)}</div><span className="filter-summary">{filtered.length} ambientes</span></div><div className="room-grid">{filtered.map(room => {
    const people = data.members.filter(p => !p.isDemo && p.callRoom === room.id);
    return <article className="room-card" key={room.id} style={{ "--room-color": room.color } as React.CSSProperties}><div className={`room-card-visual room-visual-${room.kind}`}><img src="/images/gx-office.jpg" alt={`Ambiente ${room.name}`} /><span className="room-visual-shade"/><span className="room-visual-icon"><RoomIcon kind={room.kind} size={23}/></span><span className={`room-available ${people.length ? "occupied" : ""}`}><span/>{people.length ? `${people.length} em chamada` : "Livre agora"}</span><span className="room-visual-label">GX HUB <span> / </span> {room.kind === "private" ? "EXECUTIVE" : "WORKSPACE"}</span></div><div className="room-card-body"><h2>{room.name}</h2><p>{room.description}</p><div className="room-card-meta"><span><Users size={14}/>Até {room.capacity} pessoas</span><span><Video size={14}/>Voz e vídeo</span></div><div className="room-card-actions"><button className="button button-primary" onClick={() => onJoin(room)}>Entrar na sala<ArrowUpRight size={15}/></button><button className="button button-quiet" onClick={() => onVisit(room.id)}>Ver no mapa</button></div></div></article>;
  })}<button className="room-schedule-card" onClick={onSchedule}><span className="room-schedule-symbol"><CalendarDays size={30} strokeWidth={1.3}/></span><h3>Reserve a próxima conexão.</h3><p>Escolha o melhor horário, encontre o ambiente ideal e reúna sua equipe.</p><span className="button button-secondary">Agendar uma reunião<Plus size={16}/></span></button></div><div className="workspace-note"><Check size={14}/>Todos os ambientes contam com chat, áudio e vídeo. Sua câmera só é ativada com a sua permissão.</div></div>;
}
export function TeamView({ data, onMember, onInvite }: { data: Workspace; onMember: (member: Member) => void; onInvite: () => void }) {
  const [search, setSearch] = useState(""); const [company, setCompany] = useState("all"); const [status, setStatus] = useState("all");
  const members = data.team.filter(m => `${m.name} ${m.role}`.toLowerCase().includes(search.toLowerCase()) && (company === "all" || m.company === company) && (status === "all" || m.status === status));
  return <div className="view-content"><div className="team-filters"><label className="search-field"><Search size={17}/><input placeholder="Buscar por nome ou cargo" value={search} onChange={e => setSearch(e.target.value)} aria-label="Buscar pessoas"/></label><div className="filter-select"><SlidersHorizontal size={15}/><select value={company} onChange={e => setCompany(e.target.value)} aria-label="Filtrar por empresa"><option value="all">Todas as empresas</option>{[...new Set(data.team.map(m => m.company))].map(name => <option key={name}>{name}</option>)}</select></div></div><div className="view-filter-bar"><div className="segmented-tabs">{[["all", "Toda a equipe"], ["available", "Disponíveis"], ["busy", "Em foco"], ["away", "Ausentes"]].map(([id, label]) => <button className={status === id ? "active" : ""} key={id} onClick={() => setStatus(id)}>{label}</button>)}</div><span className="filter-summary">{members.length} pessoas</span></div><div className="team-grid">{members.map(member => <button className={"team-card" + (isOnline(member.lastSeen) || member.id === data.me.id ? "" : " member-offline")} key={member.id} onClick={() => onMember(member)}><span className="team-card-top"><span className="company-mini">{member.company}</span>{isOnline(member.lastSeen) || member.id === data.me.id ? <span className={`member-status-chip ${member.status}`}><span/>{STATUS_LABELS[member.status]}</span> : <span className="member-status-chip away"><span/>Offline</span>}</span><Avatar member={member} size={62} ring={isOnline(member.lastSeen)}/><h2>{member.name}{member.isAdmin && <span className="admin-mini">admin</span>}{member.id === data.me.id && <span>você</span>}</h2><p>{member.role}</p><div className="team-card-bottom"><span><RoomIcon kind={data.rooms.find(r => r.id === member.roomId)?.kind || "reception"} size={14}/>{data.rooms.find(r => r.id === member.roomId)?.name}</span><ArrowUpRight size={16}/></div></button>)}<button className="team-invite-card" onClick={onInvite}><span><UserPlus size={27} strokeWidth={1.4}/></span><h3>Conexões que multiplicam.</h3><p>Traga mais alguém para construir com a gente.</p><strong>Convidar para o escritório<ArrowRight size={15}/></strong></button></div>{!members.length && <EmptyState icon={<Search size={26}/>} title="Nenhuma pessoa encontrada" description="Tente outro nome ou ajuste os filtros da equipe."/>}<div className="workspace-note">Cadastre sua equipe para ocupar o escritório de verdade. Membros offline aparecem esmaecidos.</div></div>;
}
function localDay(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
export function AgendaView({ data, onMeeting, onSchedule }: { data: Workspace; onMeeting: (meeting: Meeting) => void; onSchedule: () => void }) {
  const [today] = useState(() => new Date());
  const [weekOffset, setWeekOffset] = useState(0); const [selectedDay, setSelectedDay] = useState(""); const [mine, setMine] = useState(false);
  const start = new Date(today); start.setDate(today.getDate() - ((today.getDay() + 6) % 7) + weekOffset * 7); start.setHours(0, 0, 0, 0);
  const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(start); d.setDate(d.getDate() + i); return d; });
  const now = today.getTime();
  const events = data.meetings.filter(m => (selectedDay ? localDay(new Date(m.startsAt)) === selectedDay : new Date(m.startsAt).getTime() + m.duration * 60000 > now) && (!mine || m.organizerId === data.me.id));
  return <div className="view-content"><section className="agenda-calendar"><div className="agenda-calendar-heading"><h2>{start.toLocaleDateString("pt-BR", { month: "long", year: "numeric" })}</h2><div><button className="button button-quiet" onClick={() => { setWeekOffset(0); setSelectedDay(localDay(today)); }}>Hoje</button><button className="icon-button" aria-label="Semana anterior" onClick={() => setWeekOffset(v => v - 1)}><ChevronLeft size={18}/></button><button className="icon-button" aria-label="Próxima semana" onClick={() => setWeekOffset(v => v + 1)}><ChevronRight size={18}/></button></div></div><div className="week-days">{days.map(day => { const id = localDay(day); const count = data.meetings.filter(m => localDay(new Date(m.startsAt)) === id).length; return <button key={id} className={`${id === selectedDay ? "selected" : ""} ${id === localDay(today) ? "today" : ""}`} onClick={() => setSelectedDay(selectedDay === id ? "" : id)}><span>{day.toLocaleDateString("pt-BR", { weekday: "short" }).replace(".", "")}</span><strong>{day.getDate()}</strong><span className="day-events">{Array.from({ length: Math.min(count, 3) }, (_, i) => <i key={i}/>)}</span></button>; })}</div></section><div className="view-filter-bar agenda-filter"><div className="segmented-tabs"><button className={!mine ? "active" : ""} onClick={() => setMine(false)}>Agenda do workspace</button><button className={mine ? "active" : ""} onClick={() => setMine(true)}>Minhas reuniões</button></div>{selectedDay ? <button className="text-link" onClick={() => setSelectedDay("")}>Mostrar próximas reuniões</button> : <span className="filter-summary">{events.length} conexões agendadas</span>}</div><div className="agenda-events">{events.map(meeting => { const organizer = data.team.find(p => p.id === meeting.organizerId) || data.members.find(p => p.id === meeting.organizerId); return <article className="agenda-event" key={meeting.id}><div className="event-time"><strong>{timeLabel(meeting.startsAt)}</strong><span>{dayLabel(meeting.startsAt)}</span></div><span className="event-line"/><div className="event-main"><h3>{meeting.title}</h3><p>{meeting.description}</p><div><span><RoomIcon kind={data.rooms.find(r => r.id === meeting.roomId)?.kind || "meeting"} size={13}/>{data.rooms.find(r => r.id === meeting.roomId)?.name}</span><span><Clock3 size={13}/>{meeting.duration} min</span>{organizer && <span><Avatar member={organizer} size={18}/>{organizer.name.split(" ")[0]}</span>}</div></div><button className="button button-secondary" onClick={() => onMeeting(meeting)}>Ver reunião<ArrowUpRight size={15}/></button></article>; })}{!events.length && <EmptyState icon={<Coffee size={32}/>} title="Um espaço livre na sua agenda." description="Que tal marcar uma conversa e transformar uma ideia em um próximo passo?"><button className="button button-primary" onClick={onSchedule}><Plus size={16}/>Agendar reunião</button></EmptyState>}</div></div>;
}
